const labelsTr = {
    'person': 'İnsan',
    'bicycle': 'Bisiklet',
    'car': 'Araba',
    'motorcycle': 'Motosiklet',
    'airplane': 'Uçak',
    'bus': 'Otobüs',
    'train': 'Tren',
    'truck': 'Kamyon',
    'boat': 'Tekne',
    'traffic light': 'Trafik Lambası',
    'fire hydrant': 'Yangın Musluğu',
    'stop sign': 'Dur İşareti',
    'parking meter': 'Park Metresi',
    'bench': 'Bank',
    'bird': 'Kuş',
    'cat': 'Kedi',
    'dog': 'Köpek',
    'horse': 'At',
    'sheep': 'Koyun',
    'cow': 'İnek',
    'elephant': 'Fil',
    'bear': 'Ayı',
    'zebra': 'Zebra',
    'giraffe': 'Zürafa',
    'backpack': 'Sırt Çantası',
    'umbrella': 'Şemsiye',
    'handbag': 'El Çantası',
    'tie': 'Kravat',
    'suitcase': 'Valiz',
    'frisbee': 'Frizbi',
    'skis': 'Kayak',
    'snowboard': 'Kar Tahtası',
    'sports ball': 'Spor Topu',
    'kite': 'Uçurtma',
    'baseball bat': 'Beyzbol Sopası',
    'baseball glove': 'Beyzbol Eldiveni',
    'skateboard': 'Kaykay',
    'surfboard': 'Sörf Tahtası',
    'tennis racket': 'Tenis Raketi',
    'bottle': 'Şişe',
    'wine glass': 'Şarap Kadehi',
    'cup': 'Fincan/Bardak',
    'fork': 'Çatal',
    'knife': 'Bıçak',
    'spoon': 'Kaşık',
    'bowl': 'Kase',
    'banana': 'Muz',
    'apple': 'Elma',
    'sandwich': 'Sandviç',
    'orange': 'Portakal',
    'broccoli': 'Brokoli',
    'carrot': 'Havuç',
    'hot dog': 'Sosisli',
    'pizza': 'Pizza',
    'donut': 'Donat',
    'cake': 'Pasta',
    'chair': 'Sandalye',
    'couch': 'Koltuk',
    'potted plant': 'Saksı Bitkisi',
    'bed': 'Yatak',
    'dining table': 'Yemek Masası',
    'toilet': 'Tuvalet',
    'tv': 'Televizyon',
    'laptop': 'Dizüstü Bilgisayar',
    'mouse': 'Fare',
    'remote': 'Uzaktan Kumanda',
    'keyboard': 'Klavye',
    'cell phone': 'Cep Telefonu',
    'microwave': 'Mikrodalga',
    'oven': 'Fırın',
    'toaster': 'Ekmek Kızartma Makinesi',
    'sink': 'Lavabo',
    'refrigerator': 'Buzdolabı',
    'book': 'Kitap',
    'clock': 'Saat',
    'vase': 'Vazo',
    'scissors': 'Makas',
    'teddy bear': 'Oyuncak Ayı',
    'hair drier': 'Saç Kurutma Makinesi',
    'toothbrush': 'Diş Fırçası'
};

export default labelsTr;
